do_dry_run: true

#language: python
language: jvm

eval_tool: opensource
input:
  use_scripts: false
  mode: hf
  hf:
    repo_id: "envsetup-dl4c-2025/env-setup"
#    path_in_repo: readmes/python_singlerepo.jsonl
    path_in_repo: readmes/jvm.jsonl
  local: path/to/local/file
  repos_archives:
    repo_id: "envsetup-dl4c-2025/env-setup"
  columns:
    repo_name: repository
    commit_sha: revision
    script: script
output:
  mode: hf
  hf:
    repo_id: envsetup-dl4c-2025/env-setup-eval
#    path_in_repo: debug
#    path_in_repo: oss/python_full_baseline-2025-01-07
    path_in_repo: oss/jvm_full_baseline_2025-01-07
  keep_local_archives: false
  keep_local_jsonl: false
docker:
  create_container_timeout: 180
  container_timeout: 600
  envsetup_image:
    python: 'ghcr.io/envsetup-dl4c-2025/envsetup-python'
    jvm: 'ghcr.io/envsetup-dl4c-2025/envsetup-jvm'
operation:
  dirs:
    tmp: './tmp'
    repo_data: './tmp/repo_data'
    json_results: './tmp/results/json'
    envsetup_results: './tmp/results/envsetup'
  pool_config:
    max_workers: 1
    chunksize: 1
exit_codes:
  timeout: -127
  unknown_failure: -999
  docker_failure: -888
  create_container_failure: -777
  download_failure: -666
  script_failure: -555
