agent:
  agent_type: python_baseline
  toolkit: bash

  model:
    _target_: langchain_openai.ChatOpenAI
    model: gpt-4o-mini-2024-07-18
    temperature: 0

  instruction_provider:
    _target_: src.context_providers.build_instructions.SimpleREADMEEnvSetupInstructionProvider
    dataset_name: envsetup-dl4c-2025/env-setup
    language: python

  max_iterations: 30

data_source:
  type: hf

  hf:
    _target_: env_setup_utils.data_sources.HFDataSource
    hub_name: envsetup-dl4c-2025/env-setup
    configs:
      - splits
    split: python_single_dm_in_root_folder_no_docker

  local:
    _target_: env_setup_utils.data_sources.LocalFileDataSource
    path: python_repos.jsonl

docker:
  image: 'ghcr.io/envsetup-dl4c-2025/envsetup-python'
  error_message:
  command:
  env_vars: {}
  repository_workdir: true
  container_start_timeout: 300
  max_num_chars_bash_output: 16000
  bash_timeout: 360
  hf_name: envsetup-dl4c-2025/env-setup
  output_dir: /mnt/data/repos
  language: python
  clear_repo: false

hf:
  upload: true
  repo_id: envsetup-dl4c-2025/env-setup-trajectories
  path_in_repo: oss/python_baseline_langgraph_2025-01-25

#langsmith_project: env-setup-py-baseline

log_trajectory: true
logging_dir: trajectories_python_baseline_langgraph_2025-01-25
max_concurrent: 32
rewrite_trajectories: false